
"use client"; // This is a client component 👈🏽
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { createContext, useEffect, useState } from 'react'
import { lookInSession } from '@/SessionFunc';


const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Next Blog',
  description: 'Generated by create next app',
}


export const UserContext = createContext({})

export default function RootLayout({ children }) {

  const [userAuth, setUserAuth] = useState({})
  useEffect(() => {
    let userInSession = lookInSession("user")
    userInSession ? setUserAuth(JSON.parse(userInSession)) : setUserAuth({ token: null })

  }, [])

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext.Provider value={{ userAuth, setUserAuth }}>
          <Navbar />
          {children}
        </UserContext.Provider>
      </body>
    </html>
  )
}
